/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/products/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductInfo"];
                    "text/json": components["schemas"]["ProductInfo"];
                    "application/*+json": components["schemas"]["ProductInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductInfo"];
                    "text/json": components["schemas"]["ProductInfo"];
                    "application/*+json": components["schemas"]["ProductInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModuleInfo"];
                    "text/json": components["schemas"]["ModuleInfo"];
                    "application/*+json": components["schemas"]["ModuleInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModuleInfo"];
                    "text/json": components["schemas"]["ModuleInfo"];
                    "application/*+json": components["schemas"]["ModuleInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductModuleIdsRequest"];
                    "text/json": components["schemas"]["ProductModuleIdsRequest"];
                    "application/*+json": components["schemas"]["ProductModuleIdsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModuleInfo"];
                    "text/json": components["schemas"]["ModuleInfo"];
                    "application/*+json": components["schemas"]["ModuleInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModuleInfo"];
                    "text/json": components["schemas"]["ModuleInfo"];
                    "application/*+json": components["schemas"]["ModuleInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/sort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/sort/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModuleSortModel"];
                    "text/json": components["schemas"]["ModuleSortModel"];
                    "application/*+json": components["schemas"]["ModuleSortModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/module/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/checkLoginStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserForgotPasswordModel"];
                    "text/json": components["schemas"]["UserForgotPasswordModel"];
                    "application/*+json": components["schemas"]["UserForgotPasswordModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/select-product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SelectProductRequest"];
                    "text/json": components["schemas"]["SelectProductRequest"];
                    "application/*+json": components["schemas"]["SelectProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/select-productset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SelectProductSetRequest"];
                    "text/json": components["schemas"]["SelectProductSetRequest"];
                    "application/*+json": components["schemas"]["SelectProductSetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetBuyNewRequest"];
                    "text/json": components["schemas"]["GetBuyNewRequest"];
                    "application/*+json": components["schemas"]["GetBuyNewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/new-with-set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetBuyNewWithSetRequest"];
                    "text/json": components["schemas"]["GetBuyNewWithSetRequest"];
                    "application/*+json": components["schemas"]["GetBuyNewWithSetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetBuyUpgradeRequest"];
                    "text/json": components["schemas"]["GetBuyUpgradeRequest"];
                    "application/*+json": components["schemas"]["GetBuyUpgradeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/edit/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EditCartRequest"];
                    "text/json": components["schemas"]["EditCartRequest"];
                    "application/*+json": components["schemas"]["EditCartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/edit/productset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EditProductSetRequest"];
                    "text/json": components["schemas"]["EditProductSetRequest"];
                    "application/*+json": components["schemas"]["EditProductSetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BuyProductInfo"];
                    "text/json": components["schemas"]["BuyProductInfo"];
                    "application/*+json": components["schemas"]["BuyProductInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/validate-count-total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductInfoForCountTotalRequest"];
                    "text/json": components["schemas"]["ProductInfoForCountTotalRequest"];
                    "application/*+json": components["schemas"]["ProductInfoForCountTotalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy/use-productset-and-validate-count-total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductSetUseRequestInfo"];
                    "text/json": components["schemas"]["ProductSetUseRequestInfo"];
                    "application/*+json": components["schemas"]["ProductSetUseRequestInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IntIdRequest"];
                    "text/json": components["schemas"]["IntIdRequest"];
                    "application/*+json": components["schemas"]["IntIdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IntIdRequest"];
                    "text/json": components["schemas"]["IntIdRequest"];
                    "application/*+json": components["schemas"]["IntIdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangeOrderStatusRequest"];
                    "text/json": components["schemas"]["ChangeOrderStatusRequest"];
                    "application/*+json": components["schemas"]["ChangeOrderStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-sets/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/product-sets/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-sets/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GuidKeyRequest"];
                    "text/json": components["schemas"]["GuidKeyRequest"];
                    "application/*+json": components["schemas"]["GuidKeyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-sets/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductSetEditModelForAddRequestInfo"];
                    "text/json": components["schemas"]["ProductSetEditModelForAddRequestInfo"];
                    "application/*+json": components["schemas"]["ProductSetEditModelForAddRequestInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-sets/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProductSetEditModelForEditRequestInfo"];
                    "text/json": components["schemas"]["ProductSetEditModelForEditRequestInfo"];
                    "application/*+json": components["schemas"]["ProductSetEditModelForEditRequestInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-sets/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GuidKeyRequest"];
                    "text/json": components["schemas"]["GuidKeyRequest"];
                    "application/*+json": components["schemas"]["GuidKeyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRegisterModel"];
                    "text/json": components["schemas"]["UserRegisterModel"];
                    "application/*+json": components["schemas"]["UserRegisterModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GuidKeyRequest"];
                    "text/json": components["schemas"]["GuidKeyRequest"];
                    "application/*+json": components["schemas"]["GuidKeyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/register/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/register/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserCreateFromRegisterModel"];
                    "text/json": components["schemas"]["UserCreateFromRegisterModel"];
                    "application/*+json": components["schemas"]["UserCreateFromRegisterModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/register/ignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GuidKeyRequest"];
                    "text/json": components["schemas"]["GuidKeyRequest"];
                    "application/*+json": components["schemas"]["GuidKeyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetReportRequest"];
                    "text/json": components["schemas"]["GetReportRequest"];
                    "application/*+json": components["schemas"]["GetReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GetUserReportRequest"];
                    "text/json": components["schemas"]["GetUserReportRequest"];
                    "application/*+json": components["schemas"]["GetUserReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-cart/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-cart/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeleteShoppingCartItemRequest"];
                    "text/json": components["schemas"]["DeleteShoppingCartItemRequest"];
                    "application/*+json": components["schemas"]["DeleteShoppingCartItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-cart/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ShoppingCartModel"];
                    "text/json": components["schemas"]["ShoppingCartModel"];
                    "application/*+json": components["schemas"]["ShoppingCartModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserCreateModel"];
                    "text/json": components["schemas"]["UserCreateModel"];
                    "application/*+json": components["schemas"]["UserCreateModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserAdminEditModel"];
                    "text/json": components["schemas"]["UserAdminEditModel"];
                    "application/*+json": components["schemas"]["UserAdminEditModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/prepaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserChangePrepaidMoneyModel"];
                    "text/json": components["schemas"]["UserChangePrepaidMoneyModel"];
                    "application/*+json": components["schemas"]["UserChangePrepaidMoneyModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserChangeAccessModel"];
                    "text/json": components["schemas"]["UserChangeAccessModel"];
                    "application/*+json": components["schemas"]["UserChangeAccessModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserChangePasswordModel"];
                    "text/json": components["schemas"]["UserChangePasswordModel"];
                    "application/*+json": components["schemas"]["UserChangePasswordModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IdRequest"];
                    "text/json": components["schemas"]["IdRequest"];
                    "application/*+json": components["schemas"]["IdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/warehouse/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EmptyRequest"];
                    "text/json": components["schemas"]["EmptyRequest"];
                    "application/*+json": components["schemas"]["EmptyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/warehouse/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WarehouseEditModel"];
                    "text/json": components["schemas"]["WarehouseEditModel"];
                    "application/*+json": components["schemas"]["WarehouseEditModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SerialNumberRequest"];
                    "text/json": components["schemas"]["SerialNumberRequest"];
                    "application/*+json": components["schemas"]["SerialNumberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warehouse/notes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WarehouseNoteUpdateRequest"];
                    "text/json": components["schemas"]["WarehouseNoteUpdateRequest"];
                    "application/*+json": components["schemas"]["WarehouseNoteUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/warehouse/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SerialNumberRequest"];
                    "text/json": components["schemas"]["SerialNumberRequest"];
                    "application/*+json": components["schemas"]["SerialNumberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuyProductInfo: {
            ProductSetEditMode?: components["schemas"]["ProductSetEditMode"];
            Serial?: string | null;
            ID?: string | null;
            Name?: string | null;
            UseDayLicense?: boolean;
            /** Format: int32 */
            DayLicenseCount?: number;
            IsUpgrade?: boolean;
            ActionTypeDescription?: string | null;
            /** Format: uuid */
            SourceProductSetKey?: string | null;
            ProductID?: string | null;
            /** Format: double */
            OldTotal?: number;
            /** Format: double */
            NewTotal?: number;
            /** Format: date-time */
            LicenseExpiredDate?: string | null;
            /** Format: int32 */
            RemainDayLicenseCount?: number;
            /** Format: double */
            OldUnitPriceForDayLicense?: number;
            /** Format: double */
            OldTotalForDayLicense?: number;
            /** Format: double */
            TotalForDayLicense?: number;
            /** Format: double */
            TotalForBuyoutLicense?: number;
            /** Format: double */
            UpgradeCostForDayLicense?: number;
            /** Format: double */
            UnitPriceForDayLicense?: number;
            ModuleInfos?: components["schemas"]["BuyProductModuleInfo"][] | null;
        };
        BuyProductModuleInfo: {
            ParentProductID?: string | null;
            ID?: string | null;
            Name?: string | null;
            Description?: string | null;
            Detial_Description?: string | null;
            IsOnlyOne?: boolean;
            IsNecessary?: boolean;
            Currency?: string | null;
            AgainstOrderIDJoinValues?: string | null;
            AgainstOrderIDs?: string[] | null;
            IsUpgrade?: boolean;
            AllowOrderLogicRule?: string | null;
            Selected?: boolean;
            /** Format: int32 */
            OrderAmount?: number;
            /** Format: int32 */
            AlreadyOrderAmount?: number;
            /** Format: double */
            Price?: number;
            /** Format: double */
            Subtotal?: number;
            AllowOrder?: boolean;
        };
        ChangeOrderStatusRequest: {
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            StatusId?: number;
        };
        DeleteShoppingCartItemRequest: {
            /** Format: uuid */
            Key?: string;
        };
        EditCartRequest: {
            /** Format: uuid */
            CartKey?: string;
        };
        EditProductSetRequest: {
            /** Format: uuid */
            ProductSetKey?: string;
        };
        EmptyRequest: Record<string, never>;
        GetBuyNewRequest: {
            Serial?: string | null;
            ProductId?: string | null;
            EditMode?: components["schemas"]["ProductSetEditMode"];
        };
        GetBuyNewWithSetRequest: {
            Serial?: string | null;
            ProductId?: string | null;
            /** Format: uuid */
            ProductSetKey?: string;
        };
        GetBuyUpgradeRequest: {
            Serial?: string | null;
        };
        GetReportRequest: {
            /** Format: date-time */
            DateStart?: string | null;
            /** Format: date-time */
            DateEnd?: string | null;
        };
        GetUserReportRequest: {
            UserId?: string | null;
            /** Format: date-time */
            DateStart?: string | null;
            /** Format: date-time */
            DateEnd?: string | null;
        };
        GuidKeyRequest: {
            /** Format: uuid */
            Key?: string;
        };
        IdRequest: {
            Id?: string | null;
        };
        IntIdRequest: {
            /** Format: int32 */
            Id?: number;
        };
        LoginRequest: {
            UserID?: string | null;
            Password?: string | null;
        };
        ModuleInfo: {
            ParentProductID?: string | null;
            ID?: string | null;
            Name?: string | null;
            Description?: string | null;
            Detial_Description?: string | null;
            Detial_Description2?: string | null;
            IsOnlyOne?: boolean;
            IsNecessary?: boolean;
            ModulePriceTypeInfos?: components["schemas"]["ModulePriceTypeInfo"][] | null;
            AgainstOrders?: string | null;
            AllowOrderLogicRule?: string | null;
        };
        ModuleInfoForCountTotalRequest: {
            ID?: string | null;
            Selected?: boolean;
            /** Format: int32 */
            OrderAmount?: number;
        };
        ModulePriceTypeInfo: {
            /** Format: int32 */
            PriceTypeID?: number;
            PriceTypeDesc?: string | null;
            PriceFormular?: string | null;
        };
        ModuleSortInfo: {
            ID?: string | null;
            Name?: string | null;
            /** Format: int32 */
            DisplayOrder?: number;
        };
        ModuleSortModel: {
            ProductID?: string | null;
            Modules?: components["schemas"]["ModuleSortInfo"][] | null;
        };
        ProductInfo: {
            ID?: string | null;
            Name?: string | null;
            ModuleInfos?: components["schemas"]["ModuleInfo"][] | null;
        };
        ProductInfoForCountTotalRequest: {
            SerialNumber?: string | null;
            ID?: string | null;
            UseDayLicense?: boolean;
            /** Format: int32 */
            RemainDayLicenseCount?: number;
            IsUpgrade?: boolean;
            ModuleInfos?: components["schemas"]["ModuleInfoForCountTotalRequest"][] | null;
        };
        ProductModuleIdsRequest: {
            ProductId?: string | null;
            ModuleIds?: string[] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ProductSetEditMode: 0 | 1 | 2 | 3 | 4;
        ProductSetEditModelForAddRequestInfo: {
            ProductID?: string | null;
            UseDayLicense?: boolean;
            /** Format: int32 */
            DayLicenseCount?: number;
            ProductSetEditMode?: components["schemas"]["ProductSetEditMode"];
            ModuleInfos?: components["schemas"]["ProductSetModuleInfo"][] | null;
        };
        ProductSetEditModelForEditRequestInfo: {
            /** Format: uuid */
            ProductSetKey?: string;
            UseDayLicense?: boolean;
            /** Format: int32 */
            DayLicenseCount?: number;
            ProductSetEditMode?: components["schemas"]["ProductSetEditMode"];
            ProductSetName?: string | null;
            ProductSetDescription?: string | null;
            ModuleInfos?: components["schemas"]["ProductSetModuleInfo"][] | null;
        };
        ProductSetModuleInfo: {
            ModuleID?: string | null;
            ModuleName?: string | null;
            ModuleDescription?: string | null;
            /** Format: int32 */
            OrderAmount?: number;
        };
        ProductSetUseRequestInfo: {
            SerialNumber?: string | null;
            ID?: string | null;
            UseDayLicense?: boolean;
            /** Format: int32 */
            RemainDayLicenseCount?: number;
            IsUpgrade?: boolean;
            ModuleInfos?: components["schemas"]["ModuleInfoForCountTotalRequest"][] | null;
            /** Format: uuid */
            ProductSetKey?: string;
            UseType?: components["schemas"]["ProductSetUseType"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ProductSetUseType: 0 | 1;
        SelectProductRequest: {
            Serial?: string | null;
        };
        SelectProductSetRequest: {
            ProductId?: string | null;
            Serial?: string | null;
            EditMode?: components["schemas"]["ProductSetEditMode"];
        };
        SerialNumberRequest: {
            SerialNumber?: string | null;
        };
        ShoppingCartInfo: {
            /** Format: uuid */
            Key?: string;
            ProductID?: string | null;
            ProductName?: string | null;
            SerialNumber?: string | null;
            UseDayLicense?: boolean;
            /** Format: int32 */
            DayLicenseCount?: number;
            /** Format: int32 */
            RemainDayLicenseCount?: number;
            /** Format: date-time */
            LicenseExpiredDate?: string | null;
            /** Format: double */
            OldUnitPriceForDayLicense?: number;
            /** Format: double */
            UnitPriceForDayLicense?: number;
            /** Format: double */
            UpgradeCostForDayLicense?: number;
            /** Format: double */
            TotalForBuyoutLicense?: number;
            /** Format: uuid */
            UpgradeSourceOrderProductKey?: string | null;
            IsUpgrade?: boolean;
            /** Format: double */
            OldTotalForDayLicense?: number;
            /** Format: double */
            TotalForDayLicense?: number;
            /** Format: double */
            OldTotal?: number;
            /** Format: double */
            NewTotal?: number;
            /** Format: double */
            UpgradeCost?: number;
            readonly DayLicenseIsExpired?: boolean;
            ModuleInfos?: components["schemas"]["ShoppingCartModuleInfo"][] | null;
        };
        ShoppingCartModel: {
            /** Format: int32 */
            PaymentTypeID?: number;
            /** Format: double */
            UserPrePaidMoney?: number;
            /** Format: double */
            Total?: number;
            Infos?: components["schemas"]["ShoppingCartInfo"][] | null;
        };
        ShoppingCartModuleInfo: {
            /** Format: uuid */
            Key?: string;
            ParentProductID?: string | null;
            ID?: string | null;
            Name?: string | null;
            Description?: string | null;
            Selected?: boolean;
            /** Format: int32 */
            OrderAmount?: number;
            IsUpgrade?: boolean;
            /** Format: int32 */
            AlreadyOrderAmount?: number;
            /** Format: double */
            Price?: number;
            /** Format: double */
            Subtotal?: number;
            AllowOrder?: boolean;
        };
        UserAccessData: {
            Type?: components["schemas"]["UserAccessType"];
            Value?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        UserAccessType: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        UserAdminEditModel: {
            ID?: string | null;
            DisplayName?: string | null;
            Phone?: string | null;
            Email?: string | null;
            /** Format: int32 */
            RoleID?: number;
            /** Format: int32 */
            LanguageID?: number;
        };
        UserChangeAccessModel: {
            ID?: string | null;
            Accesses?: components["schemas"]["UserAccessData"][] | null;
        };
        UserChangePasswordModel: {
            OldPassword?: string | null;
            NewPassword?: string | null;
            ConfirmPassword?: string | null;
        };
        UserChangePrepaidMoneyModel: {
            ID?: string | null;
            DisplayName?: string | null;
            Phone?: string | null;
            Email?: string | null;
            RoleDescription?: string | null;
            /** Format: double */
            PrepaidMoney?: number;
            /** Format: double */
            NewPrepaidMoney?: number;
        };
        UserCreateFromRegisterModel: {
            /** Format: uuid */
            Key?: string;
            ID?: string | null;
            DisplayName?: string | null;
            Phone?: string | null;
            Email?: string | null;
            /** Format: date-time */
            RegisterDateTime?: string;
            /** Format: int32 */
            RoleID?: number;
            /** Format: int32 */
            LanguageID?: number;
        };
        UserCreateModel: {
            ID?: string | null;
            DisplayName?: string | null;
            Password?: string | null;
            Phone?: string | null;
            Email?: string | null;
            /** Format: int32 */
            RoleID?: number;
            /** Format: int32 */
            LanguageID?: number;
        };
        UserForgotPasswordModel: {
            ID?: string | null;
            Email?: string | null;
        };
        UserRegisterModel: {
            ID?: string | null;
            DisplayName?: string | null;
            Password?: string | null;
            Phone?: string | null;
            Email?: string | null;
            /** Format: int32 */
            LanguageID?: number;
        };
        WarehouseEditModel: {
            SerialNumber?: string | null;
            MachineCode?: string | null;
            UserID?: string | null;
            NoteText?: string | null;
        };
        WarehouseNoteUpdateRequest: {
            SerialNumber?: string | null;
            NoteText?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
